### ISSUE TITLE
train_pose.py --ValueError

### ISSUE THREAD

**Issue by xiakun123** [Xiangyu-CAS/Realtime_Multi-Person_Pose_Estimation.PyTorch#4]
Traceback (most recent call last):
  File "train_pose.py", line 317, in <module>
    train_val(model, args)
  File "train_pose.py", line 170, in train_val
    for i, (input, heatmap, vecmap, mask, kpt) in enumerate(train_loader):
  File "/home/wanghaoran/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 314, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/wanghaoran/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 314, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "../../coco_loader.py", line 211, in __getitem__
    img, mask, kpt, center = self.transformer(img, mask, kpt, center, scale)
  File "../../Mytransforms.py", line 445, in __call__
    img, mask, kpt, center = t(img, mask, kpt, center)
  File "../../Mytransforms.py", line 370, in __call__
    return crop(img, mask, kpt, center, offset_left, offset_up, self.size[0], self.size[1])
  File "../../Mytransforms.py", line 314, in crop
    new_img[st_y: ed_y, st_x: ed_x, :] = img[or_st_y: or_ed_y, or_st_x: or_ed_x, :].copy()
ValueError: could not broadcast input array from shape (219,0,3) into shape (219,262,3)
Why is this a problem? @Xiangyu-CAS

**Comment by Xiangyu-CAS** [comment]
Obviously, shape (219,0,3) means the width of image is 0, in another word, when you crop the image by using "new_img[st_y: ed_y, st_x: ed_x, :]", st_x is greater than ed_x.
